


export interface SkillType {
    name: string;
    category: CategoryEnum
  }

  export enum CategoryEnum {
    Takedown = 'Takedown',
    Pass = 'Pass',
    Control = 'Control',
    Submission = 'Submission',
    Escape = 'Escape',
    Guard = 'Guard',
    Sweep = 'Sweep',
    System = 'System',
    None = 'None',
  }
  
  export const Skills: SkillType[] = [
    { name: 'Single Leg', category: CategoryEnum.Takedown },
    { name: 'Double Leg', category: CategoryEnum.Takedown },
    { name: 'Body Lock', category: CategoryEnum.Takedown },
    { name: 'Foot Sweep', category: CategoryEnum.Takedown },
    { name: 'Ankle Pick', category: CategoryEnum.Takedown },
    { name: 'Arm Drag', category: CategoryEnum.Takedown },
    { name: 'Fireman\'s Carry', category: CategoryEnum.Takedown },
    { name: 'Tomoe Nage', category: CategoryEnum.Takedown },
    { name: 'Knee Cut', category: CategoryEnum.Pass },
    { name: 'Leg Drag', category: CategoryEnum.Pass },
    { name: 'Torreando', category: CategoryEnum.Pass },
    { name: 'Over Under', category: CategoryEnum.Pass },   
    { name: 'Tripod', category: CategoryEnum.Pass },
    { name: 'Body Lock', category: CategoryEnum.Pass },
    { name: 'Stack Pass', category: CategoryEnum.Pass },
    { name: 'X Pass', category: CategoryEnum.Pass },
    { name: 'Smash Pass', category: CategoryEnum.Pass },
    { name: 'Back Step', category: CategoryEnum.Pass },
    { name: 'Leg Weave', category: CategoryEnum.Pass },
    { name: 'Berimbolo', category: CategoryEnum.Pass },
    { name: 'Side Control', category: CategoryEnum.Control },
    { name: 'Mount', category: CategoryEnum.Control },
    { name: 'Back Control', category: CategoryEnum.Control },
    { name: 'Knee on Belly', category: CategoryEnum.Control },
    { name: 'North South', category: CategoryEnum.Control },
    { name: 'AShi Grami', category: CategoryEnum.Control },
    { name: 'Crucifix', category: CategoryEnum.Control },
    { name: 'Leg Ride', category: CategoryEnum.Control },
    { name: 'Wrestling Pin', category: CategoryEnum.Control },
    { name: 'Choke', category: CategoryEnum.Submission },
    { name: 'Armbar', category: CategoryEnum.Submission },
    { name: 'Kimura', category: CategoryEnum.Submission },
    { name: 'Triangle', category: CategoryEnum.Submission },
    { name: 'Rear Naked Choke', category: CategoryEnum.Submission },
    { name: 'Guillotine', category: CategoryEnum.Submission },
    { name: 'Americana', category: CategoryEnum.Submission },
    { name: 'Omoplata', category: CategoryEnum.Submission },
    { name: 'Heel Hook', category: CategoryEnum.Submission },
    { name: 'Knee Bar', category: CategoryEnum.Submission },
    { name: 'Toe Hold', category: CategoryEnum.Submission },
    { name: 'Ezekiel', category: CategoryEnum.Submission },
    { name: 'Wrist Lock', category: CategoryEnum.Submission },
    { name: 'Neck Crank', category: CategoryEnum.Submission },
    { name: 'Calf Slicer', category: CategoryEnum.Submission },
    { name: 'Shoulder Lock', category: CategoryEnum.Submission },
    { name: 'Leg Lock', category: CategoryEnum.Submission },
    { name: 'Side Control Escape', category: CategoryEnum.Escape },
    { name: 'Mount Escape', category: CategoryEnum.Escape },
    { name: 'Back Escape', category: CategoryEnum.Escape },
    { name: 'Knee on Belly Escape', category: CategoryEnum.Escape },
    { name: 'North South Escape', category: CategoryEnum.Escape },
    { name: 'Closed Guard', category: CategoryEnum.Guard },
    { name: 'Open Guard', category: CategoryEnum.Guard },
    { name: 'Half Guard', category: CategoryEnum.Guard },
    { name: 'Butterfly Guard', category: CategoryEnum.Guard },
    { name: 'Spider Guard', category: CategoryEnum.Guard },
    { name: 'De La Riva', category: CategoryEnum.Guard },
    { name: 'Reverse De La Riva', category: CategoryEnum.Guard },
    { name: 'Lasso Guard', category: CategoryEnum.Guard },
    { name: 'X Guard', category: CategoryEnum.Guard },
    { name: 'Rubber Guard', category: CategoryEnum.Guard },
    { name: '50/50', category: CategoryEnum.Guard },
    { name: 'Deep Half Guard', category: CategoryEnum.Guard },
    { name: 'Scissor Sweep', category: CategoryEnum.Sweep },
    { name: 'Butterfly Sweep', category: CategoryEnum.Sweep },
    { name: 'Game Plan', category: CategoryEnum.System },
    { name: 'Concept', category: CategoryEnum.System },
    { name: 'Strategy', category: CategoryEnum.System },
    { name: 'Principle', category: CategoryEnum.System },

  ]

  // For backward compatibility
  export const CategorySkillMap: { [key: string]: string[] } = {
      Takedown: ['Single Leg', 'Double Leg', 'Body Lock', 'Foot Sweep', 'Ankle Pick', 'Arm Drag', 'Fireman\'s Carry', 'Tomoe Nage'],
      Pass: ['Knee Cut', 'Leg Drag', 'Torreando', 'Over Under', 'Tripod', 'Body Lock','Stack Pass', 'X Pass', 'Smash Pass', 'Back Step', 'Leg Weave', 'Berimbolo'],
      Control: ['Side Control', 'Mount', 'Back Control', 'Knee on Belly', 'North South', ' AShi Grami', 'Crucifix','Leg Ride', 'Wrestling Pin'],
      Submission: ['Choke', 'Armbar', 'Kimura', 'Triangle', 'Rear Naked Choke', 'Guillotine', 'Americana', 'Omoplata', 'Heel Hook', 'Knee Bar', 'Toe Hold', 'Ezekiel', 'Wrist Lock', 'Neck Crank', 'Calf Slicer', 'Shoulder Lock', 'Leg Lock'],
      Escape: ['Side Control Escape', 'Mount Escape', 'Back Escape', 'Knee on Belly Escape', 'North South Escape'],
      Guard: ['Closed Guard', 'Open Guard', 'Half Guard', 'Butterfly Guard', 'Spider Guard', 'De La Riva', 'Reverse De La Riva', 'Lasso Guard', 'X Guard', 'Rubber Guard', '50/50', 'Deep Half Guard'],
      Sweep: ['Scissor Sweep', 'Butterfly Sweep'],
      System: ['Game Plan', 'Concept', 'Strategy', 'Principle'],
  };
  