export interface SkillType {
  id: string;
  title: string;
  category: string;
}

export const Categories: string[] = ['Takedown', 'Pass', 'Control', 'Submission', 'Escape', 'Guard', 'Sweep', 'System'];

export const CategorySkillMap: { [key: string]: string[] } = {
    Takedown: ['Single Leg', 'Double Leg', 'Body Lock', 'Foot Sweep', 'Ankle Pick', 'Arm Drag', 'Fireman\'s Carry', 'Tomoe Nage'],
    Pass: ['Knee Cut', 'Leg Drag', 'Torreando', 'Over Under', 'Tripod', 'Body Lock','Stack Pass', 'X Pass', 'Smash Pass', 'Back Step', 'Leg Weave', 'Berimbolo'],
    Control: ['Side Control', 'Mount', 'Back Control', 'Knee on Belly', 'North South', ' AShi Grami', 'Crucifix','Leg Ride', 'Wrestling Pin'],
    Submission: ['Choke', 'Armbar', 'Kimura', 'Triangle', 'Rear Naked Choke', 'Guillotine', 'Americana', 'Omoplata', 'Heel Hook', 'Knee Bar', 'Toe Hold', 'Ezekiel', 'Wrist Lock', 'Neck Crank', 'Calf Slicer', 'Shoulder Lock', 'Leg Lock'],
    Escape: ['Side Control Escape', 'Mount Escape', 'Back Escape', 'Knee on Belly Escape', 'North South Escape'],
    Guard: ['Closed Guard', 'Open Guard', 'Half Guard', 'Butterfly Guard', 'Spider Guard', 'De La Riva', 'Reverse De La Riva', 'Lasso Guard', 'X Guard', 'Rubber Guard', '50/50', 'Deep Half Guard'],
    Sweep: ['Scissor Sweep', 'Butterfly Sweep'],
    System: ['Game Plan', 'Concept', 'Strategy', 'Principle'],
};

export const Skills: SkillType[] = [
    { id: '0-0', title: 'Single Leg', category: 'Takedown' },
    { id: '0-1', title: 'Double Leg', category: 'Takedown' },
    { id: '0-2', title: 'Body Lock', category: 'Takedown' },
    { id: '0-3', title: 'Foot Sweep', category: 'Takedown' },
    { id: '0-4', title: 'Ankle Pick', category: 'Takedown' },
    { id: '0-5', title: 'Arm Drag', category: 'Takedown' },
    { id: '0-6', title: 'Fireman\'s Carry', category: 'Takedown' },
    { id: '0-7', title: 'Tomoe Nage', category: 'Takedown' },
    { id: '1-0', title: 'Knee Cut', category: 'Pass' },
    { id: '1-1', title: 'Leg Drag', category: 'Pass' },
    { id: '1-2', title: 'Torreando', category: 'Pass' },
    { id: '1-3', title: 'Over Under', category: 'Pass' },
    { id: '1-4', title: 'Tripod', category: 'Pass' },
    { id: '1-5', title: 'Body Lock', category: 'Pass' },
    { id: '1-6', title: 'Stack Pass', category: 'Pass' },
    { id: '1-7', title: 'X Pass', category: 'Pass' },
    { id: '1-8', title: 'Smash Pass', category: 'Pass' },
    { id: '1-9', title: 'Back Step', category: 'Pass' },
    { id: '1-10', title: 'Leg Weave', category: 'Pass' },
    { id: '1-11', title: 'Berimbolo', category: 'Pass' },
    { id: '2-0', title: 'Side Control', category: 'Control' },
    { id: '2-1', title: 'Mount', category: 'Control' },
    { id: '2-2', title: 'Back Control', category: 'Control' },
    { id: '2-3', title: 'Knee on Belly', category: 'Control' },
    { id: '2-4', title: 'North South', category: 'Control' },
    { id: '2-5', title: 'AShi Grami', category: 'Control' },
    { id: '2-6', title: 'Crucifix', category: 'Control' },
    { id: '2-7', title: 'Leg Ride', category: 'Control' },
    { id: '2-8', title: 'Wrestling Pin', category: 'Control' },
    { id: '3-0', title: 'Choke', category: 'Submission' },
    { id: '3-1', title: 'Armbar', category: 'Submission' },
    { id: '3-2', title: 'Kimura', category: 'Submission' },
    { id: '3-3', title: 'Triangle', category: 'Submission' },
    { id: '3-4', title: 'Rear Naked Choke', category: 'Submission' },
    { id: '3-5', title: 'Guillotine', category: 'Submission' },
    { id: '3-6', title: 'Americana', category: 'Submission' },
    { id: '3-7', title: 'Omoplata', category: 'Submission' },
    { id: '3-8', title: 'Heel Hook', category: 'Submission' },
    { id: '3-9', title: 'Knee Bar', category: 'Submission' },
    { id: '3-10', title: 'Toe Hold', category: 'Submission' },
    { id: '3-11', title: 'Ezekiel', category: 'Submission' },
    { id: '3-12', title: 'Wrist Lock', category: 'Submission' },
    { id: '3-13', title: 'Neck Crank', category: 'Submission' },
    { id: '3-14', title: 'Calf Slicer', category: 'Submission' },
    { id: '3-15', title: 'Shoulder Lock', category: 'Submission' },
    { id: '3-16', title: 'Leg Lock', category: 'Submission' },
    { id: '4-0', title: 'Side Control Escape', category: 'Escape' },
    { id: '4-1', title: 'Mount Escape', category: 'Escape' },
    { id: '4-2', title: 'Back Escape', category: 'Escape' },
    { id: '4-3', title: 'Knee on Belly Escape', category: 'Escape' },
    { id: '4-4', title: 'North South Escape', category: 'Escape' },
    { id: '5-0', title: 'Closed Guard', category: 'Guard' },
    { id: '5-1', title: 'Open Guard', category: 'Guard' },
    { id: '5-2', title: 'Half Guard', category: 'Guard' },
    { id: '5-3', title: 'Butterfly Guard', category: 'Guard' },
    { id: '5-4', title: 'Spider Guard', category: 'Guard' },
    { id: '5-5', title: 'De La Riva', category: 'Guard' },
    { id: '5-6', title: 'Reverse De La Riva', category: 'Guard' },
    { id: '5-7', title: 'Lasso Guard', category: 'Guard' },
    { id: '5-8', title: 'X Guard', category: 'Guard' },
    { id: '5-9', title: 'Rubber Guard', category: 'Guard' },
    { id: '5-10', title: '50/50', category: 'Guard' },
    { id: '5-11', title: 'Deep Half Guard', category: 'Guard' },
    { id: '6-0', title: 'Scissor Sweep', category: 'Sweep' },
    { id: '6-1', title: 'Butterfly Sweep', category: 'Sweep' },
    { id: '7-0', title: 'Game Plan', category: 'System' },
    { id: '7-1', title: 'Concept', category: 'System' },
    { id: '7-2', title: 'Strategy', category: 'System' },
    { id: '7-3', title: 'Principle', category: 'System' },
];