export interface SkillType {
  id: string;
  name: string;
  category: string;
}

export const Categories: string[] = ['Takedown', 'Pass', 'Control', 'Submission', 'Escape', 'Guard', 'Sweep', 'System'];

export const CategorySkillMap: { [key: string]: string[] } = {
    Takedown: ['Single Leg', 'Double Leg', 'Body Lock', 'Foot Sweep', 'Ankle Pick', 'Arm Drag', 'Fireman\'s Carry', 'Tomoe Nage'],
    Pass: ['Knee Cut', 'Leg Drag', 'Torreando', 'Over Under', 'Tripod', 'Body Lock','Stack Pass', 'X Pass', 'Smash Pass', 'Back Step', 'Leg Weave', 'Berimbolo'],
    Control: ['Side Control', 'Mount', 'Back Control', 'Knee on Belly', 'North South', ' AShi Grami', 'Crucifix','Leg Ride', 'Wrestling Pin'],
    Submission: ['Choke', 'Armbar', 'Kimura', 'Triangle', 'Rear Naked Choke', 'Guillotine', 'Americana', 'Omoplata', 'Heel Hook', 'Knee Bar', 'Toe Hold', 'Ezekiel', 'Wrist Lock', 'Neck Crank', 'Calf Slicer', 'Shoulder Lock', 'Leg Lock'],
    Escape: ['Side Control Escape', 'Mount Escape', 'Back Escape', 'Knee on Belly Escape', 'North South Escape'],
    Guard: ['Closed Guard', 'Open Guard', 'Half Guard', 'Butterfly Guard', 'Spider Guard', 'De La Riva', 'Reverse De La Riva', 'Lasso Guard', 'X Guard', 'Rubber Guard', '50/50', 'Deep Half Guard'],
    Sweep: ['Scissor Sweep', 'Butterfly Sweep'],
    System: ['Game Plan', 'Concept', 'Strategy', 'Principle'],
};

export const Skills: SkillType[] = [
    { id: '0-0', name: 'Single Leg', category: 'Takedown' },
    { id: '0-1', name: 'Double Leg', category: 'Takedown' },
    { id: '0-2', name: 'Body Lock', category: 'Takedown' },
    { id: '0-3', name: 'Foot Sweep', category: 'Takedown' },
    { id: '0-4', name: 'Ankle Pick', category: 'Takedown' },
    { id: '0-5', name: 'Arm Drag', category: 'Takedown' },
    { id: '0-6', name: 'Fireman\'s Carry', category: 'Takedown' },
    { id: '0-7', name: 'Tomoe Nage', category: 'Takedown' },
    { id: '1-0', name: 'Knee Cut', category: 'Pass' },
    { id: '1-1', name: 'Leg Drag', category: 'Pass' },
    { id: '1-2', name: 'Torreando', category: 'Pass' },
    { id: '1-3', name: 'Over Under', category: 'Pass' },
    { id: '1-4', name: 'Tripod', category: 'Pass' },
    { id: '1-5', name: 'Body Lock', category: 'Pass' },
    { id: '1-6', name: 'Stack Pass', category: 'Pass' },
    { id: '1-7', name: 'X Pass', category: 'Pass' },
    { id: '1-8', name: 'Smash Pass', category: 'Pass' },
    { id: '1-9', name: 'Back Step', category: 'Pass' },
    { id: '1-10', name: 'Leg Weave', category: 'Pass' },
    { id: '1-11', name: 'Berimbolo', category: 'Pass' },
    { id: '2-0', name: 'Side Control', category: 'Control' },
    { id: '2-1', name: 'Mount', category: 'Control' },
    { id: '2-2', name: 'Back Control', category: 'Control' },
    { id: '2-3', name: 'Knee on Belly', category: 'Control' },
    { id: '2-4', name: 'North South', category: 'Control' },
    { id: '2-5', name: 'AShi Grami', category: 'Control' },
    { id: '2-6', name: 'Crucifix', category: 'Control' },
    { id: '2-7', name: 'Leg Ride', category: 'Control' },
    { id: '2-8', name: 'Wrestling Pin', category: 'Control' },
    { id: '3-0', name: 'Choke', category: 'Submission' },
    { id: '3-1', name: 'Armbar', category: 'Submission' },
    { id: '3-2', name: 'Kimura', category: 'Submission' },
    { id: '3-3', name: 'Triangle', category: 'Submission' },
    { id: '3-4', name: 'Rear Naked Choke', category: 'Submission' },
    { id: '3-5', name: 'Guillotine', category: 'Submission' },
    { id: '3-6', name: 'Americana', category: 'Submission' },
    { id: '3-7', name: 'Omoplata', category: 'Submission' },
    { id: '3-8', name: 'Heel Hook', category: 'Submission' },
    { id: '3-9', name: 'Knee Bar', category: 'Submission' },
    { id: '3-10', name: 'Toe Hold', category: 'Submission' },
    { id: '3-11', name: 'Ezekiel', category: 'Submission' },
    { id: '3-12', name: 'Wrist Lock', category: 'Submission' },
    { id: '3-13', name: 'Neck Crank', category: 'Submission' },
    { id: '3-14', name: 'Calf Slicer', category: 'Submission' },
    { id: '3-15', name: 'Shoulder Lock', category: 'Submission' },
    { id: '3-16', name: 'Leg Lock', category: 'Submission' },
    { id: '4-0', name: 'Side Control Escape', category: 'Escape' },
    { id: '4-1', name: 'Mount Escape', category: 'Escape' },
    { id: '4-2', name: 'Back Escape', category: 'Escape' },
    { id: '4-3', name: 'Knee on Belly Escape', category: 'Escape' },
    { id: '4-4', name: 'North South Escape', category: 'Escape' },
    { id: '5-0', name: 'Closed Guard', category: 'Guard' },
    { id: '5-1', name: 'Open Guard', category: 'Guard' },
    { id: '5-2', name: 'Half Guard', category: 'Guard' },
    { id: '5-3', name: 'Butterfly Guard', category: 'Guard' },
    { id: '5-4', name: 'Spider Guard', category: 'Guard' },
    { id: '5-5', name: 'De La Riva', category: 'Guard' },
    { id: '5-6', name: 'Reverse De La Riva', category: 'Guard' },
    { id: '5-7', name: 'Lasso Guard', category: 'Guard' },
    { id: '5-8', name: 'X Guard', category: 'Guard' },
    { id: '5-9', name: 'Rubber Guard', category: 'Guard' },
    { id: '5-10', name: '50/50', category: 'Guard' },
    { id: '5-11', name: 'Deep Half Guard', category: 'Guard' },
    { id: '6-0', name: 'Scissor Sweep', category: 'Sweep' },
    { id: '6-1', name: 'Butterfly Sweep', category: 'Sweep' },
    { id: '7-0', name: 'Game Plan', category: 'System' },
    { id: '7-1', name: 'Concept', category: 'System' },
    { id: '7-2', name: 'Strategy', category: 'System' },
    { id: '7-3', name: 'Principle', category: 'System' },
];